const {chromium}=require('/Users/liweng/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');let checks=[];const check=(label,value)=>{assert(value,label);checks.push(label);};
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});
for(const [width,height] of [[1920,1080],[1280,720]]){const dir=path.join(__dirname,`${width}×${height}`);const ctx=await b.newContext({viewport:{width,height},deviceScaleFactor:1});const p=await ctx.newPage();const errors=[];const external=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});const click=async a=>{await p.locator(`[data-action="${a}"]`).first().click();};const nav=async v=>p.locator(`[data-nav="${v}"]`).click();const state=()=>p.evaluate(()=>JSON.parse(JSON.stringify(s)));const screenshot=async name=>{await p.locator('.scene img').evaluate(e=>e.decode());await p.waitForTimeout(1150);await p.screenshot({path:path.join(dir,name+'.png')});};
await p.goto(pathToFileURL(path.join(root,'直接打开.html')).href);check(`${width}开局库存`,JSON.stringify(await state())===JSON.stringify(await p.evaluate(()=>initial())));await screenshot('01_工位链全景');
await nav('stage');check(`${width}未制作不能上场`,await p.evaluate(()=>view==='home'));await click('go-loom');check(`${width}走近只一个主提示`,await p.locator('.plaque .primary').count()===1);await click('enter');await screenshot('02_织机确认开局绢');await p.keyboard.press('Escape');check(`${width}取消退一步`,await p.evaluate(()=>view==='loom'&&step==='approach'&&!s.seen));await click('enter');await click('confirm-cloth');check(`${width}确认后不提供重复确认`,await p.locator('[data-action="confirm-cloth"]').count()===0);check(`${width}确认不新增布`,(await state()).cloth===8);
await click('go-dye');await click('enter');check(`${width}未取染料不能浸染`,await p.locator('[data-action="start-dye"]').isDisabled());await click('powder');await screenshot('03_染缸取料');await click('start-dye');await click('stir');await p.keyboard.press('Escape');check(`${width}起布前取消不扣料`,(await state()).indigo===2);await click('start-dye');for(let i=0;i<3;i++)await click('stir');await click('lift');check(`${width}起布扣一份靛蓝`,(await state()).indigo===1&&(await state()).dyed);await nav('dye');await click('enter');check(`${width}重入染缸不重扣`,(await state()).indigo===1);
await click('go-cut');await click('enter');await p.locator('[data-cloth]').dragTo(p.locator('.dropzone'));check(`${width}拖布真实铺好`,await p.locator('.dropzone').evaluate(e=>e.textContent.includes('已铺好')));await p.locator('[data-key="seam"][data-value="正面"]').click();check(`${width}拼缝有图标和文字`,await p.locator('.warning').innerText().then(t=>t.includes('⚠')&&t.includes('正面')));await screenshot('04_裁桌拼缝警告');await p.locator('[data-key="seam"][data-value="侧边"]').click();await click('cut-piece');check(`${width}上襦用2.5米`,(await state()).cloth===5.5);await click('next-cut');await click('place');await click('cut-piece');check(`${width}裙用3米`,(await state()).cloth===2.5);await click('prepare-sash');await click('place');await click('cut-piece');check(`${width}未完成披帛与余布守恒`,(await state()).cloth===1&&(await state()).parts.find(x=>x.name==='披帛').sewn===false);await screenshot('05_留下未缝披帛');
await click('go-sew');await click('enter');await screenshot('06_沿缝操作');for(let i=0;i<6;i++)await click('stitch');check(`${width}衣片完成披帛保留`,(await state()).parts.filter(x=>x.sewn).length===2);check(`${width}详情默认折叠`,await p.locator('.plaque details').evaluate(e=>!e.open));check(`${width}词条不超三个`,await p.locator('.badge').count()<=3);await screenshot('07_缝合完成');
await click('go-mannequin');await click('enter');await screenshot('08_人台试衣');await click('compare');await screenshot('09_素纱与绸透光');check(`${width}材料对照不加库存`,(await state()).cloth===1&&(await state()).parts.length===3);await click('back');await click('inspect');check(`${width}人台后才能收成衣`,(await state()).inspected&&(await state()).collected);
await click('go-stage');await click('enter');check(`${width}上场只有西施`,await p.locator('.plaque').innerText().then(t=>t.includes('西施')&&!t.includes('昭君')&&!t.includes('飞燕')));await screenshot('10_西施上场门');await click('play');check(`${width}演出只留暂停`,await p.locator('button:visible').count()===1&&await p.locator('[data-action="pause"]').isVisible());check(`${width}字幕默认开`,await p.locator('.subtitle').isVisible());await p.waitForTimeout(1600);await screenshot('11_西施0档演出');await click('pause');const before=await p.evaluate(()=>play.elapsed);await p.waitForTimeout(800);check(`${width}暂停停止进度`,await p.evaluate(()=>play.elapsed)===before);await screenshot('12_演出暂停');await p.keyboard.press('Space');await p.locator('[data-action="go-cabinet"]').waitFor({state:'visible',timeout:16000});check(`${width}演出真实完成`,(await state()).performed);
await click('go-cabinet');await click('enter');check(`${width}放入前是空柜`,await p.locator('.scene img').getAttribute('alt').then(t=>t.includes('空展柜')));await screenshot('12b_展柜放入前');await click('put-cabinet');check(`${width}放入后展柜有衣`,await p.locator('.scene img').getAttribute('alt').then(t=>!t.includes('空展柜')));await p.locator('#exhibit-title').fill('靛蓝初衣 · 春日');await click('save-caption');check(`${width}入柜与标题更新`,(await state()).exhibited&&(await state()).title==='靛蓝初衣 · 春日');check(`${width}入柜成衣从侧架移走`,await p.locator('.rail .garment').count()===0);check(`${width}单柜无收益`,(await state()).money===40&&(await state()).level===1);await screenshot('13_展柜单柜预览');await click('edit-caption');await p.locator('#exhibit-title').fill('尚未确认的标题');await p.locator('[data-caption="raw"]').uncheck();await p.keyboard.press('Escape');check(`${width}取消说明牌不写入`,(await state()).title==='靛蓝初衣 · 春日'&&(await state()).caption.raw);await click('edit-caption');await p.locator('[data-caption="raw"]').uncheck();await click('save-caption');check(`${width}说明牌开关生效`,!await p.locator('.annotation').innerText().then(t=>t.includes('平纹绢')));await click('settings');await p.locator('[data-pref="text"]').selectOption('放大');await p.locator('[data-pref="reduced"]').check();await screenshot('14_文字放大与减少动效');await click('settings-close');check(`${width}页面不横向溢出`,await p.evaluate(()=>document.documentElement.scrollWidth===innerWidth));check(`${width}侧架不遮走廊`,await p.locator('.rail').evaluate(e=>e.getBoundingClientRect().bottom<=document.querySelector('.nav').getBoundingClientRect().top));
await p.reload();check(`${width}独立进度恢复`,(await state()).exhibited&&(await state()).indigo===1&&(await state()).cloth===1);await click('settings');await click('ask-reset');await click('cancel-reset');check(`${width}取消重置保留进度`,(await state()).exhibited);await click('ask-reset');await click('reset');check(`${width}重新体验恢复开局`,(await state()).cloth===8&&(await state()).indigo===2&&!(await state()).exhibited);
check(`${width}无页面错误`,errors.length===0);check(`${width}无联网请求`,external.length===0);await ctx.close();console.log(`通过 ${width}×${height} 完整流程与边界检查`);}

const badCtx=await b.newContext({viewport:{width:1280,height:720}});const bad=await badCtx.newPage();await bad.goto(pathToFileURL(path.join(root,'直接打开.html')).href);const tap=async a=>bad.locator(`[data-action="${a}"]`).first().click();await tap('go-loom');await tap('enter');await tap('confirm-cloth');await tap('go-dye');await tap('enter');await tap('powder');await tap('start-dye');for(let i=0;i<3;i++)await tap('stir');await tap('lift');await tap('go-cut');await tap('enter');await tap('place');await bad.locator('[data-key="seam"][data-value="正面"]').click();await tap('cut-piece');await tap('next-cut');await tap('place');await bad.locator('[data-key="seam"][data-value="侧边"]').click();await tap('cut-piece');await tap('go-sew');await tap('enter');for(let i=0;i<6;i++)await tap('stitch');check('不妥拼缝改变展示档位',await bad.locator('.grade').innerText().then(t=>t==='普通'));check('不妥拼缝不显示合制词条',await bad.locator('.badge').count()===0);check('不妥拼缝保留衣片并守恒',await bad.evaluate(()=>s.parts.length===2&&s.cloth===2.5));await badCtx.close();
require('node:child_process').execFileSync('python3',[path.join(root,'生成效果总览.py')]);const galleryCtx=await b.newContext({viewport:{width:1280,height:720}});const gallery=await galleryCtx.newPage();await gallery.goto(pathToFileURL(path.join(root,'效果总览.html')).href);await gallery.locator('img').evaluateAll(els=>els.forEach(e=>e.loading='eager'));await gallery.locator('img').evaluateAll(els=>Promise.all(els.map(e=>e.decode())));check('总览全部图片能打开',await gallery.locator('img').evaluateAll(els=>els.length===36&&els.every(e=>e.naturalWidth>0)));await gallery.locator('[data-res="1280×720"]').click();check('总览可切换验收尺寸',await gallery.locator('[data-resolution="1280×720"]').isVisible()&&!await gallery.locator('[data-resolution="1920×1080"]').isVisible());await gallery.screenshot({path:path.join(__dirname,'效果总览_1280×720.png')});await galleryCtx.close();
const ctx=await b.newContext();const p=await ctx.newPage();const isolated='/private/tmp/华裳直接打开-独立验证.html';fs.copyFileSync(path.join(root,'直接打开.html'),isolated);await p.goto(pathToFileURL(isolated).href);await p.locator('.scene img').evaluate(e=>e.decode());check('单文件脱离素材目录仍能显示',await p.locator('.scene img').evaluate(e=>e.complete&&e.naturalWidth>0));await p.locator('[data-action="go-loom"]').click();check('单文件操作有效',await p.evaluate(()=>view==='loom'));fs.unlinkSync(isolated);await ctx.close();await b.close();fs.writeFileSync(path.join(__dirname,'检查结果.json'),JSON.stringify({date:'2026-10-03',checks,count:checks.length},null,2));console.log(`合计${checks.length}项通过`);
})().catch(e=>{console.error(e);process.exit(1)});
