from pathlib import Path
from html import escape
root=Path(__file__).resolve().parent
concepts=[('工位链全景','经线、液面、裁桌与人台连成一条路。'),('染缸特写','湿布、靛蓝与一口陶缸；反光克制。'),('人台','看清领口、腰线与衣褶。'),('古典木色戏台','木色背景暗于衣服，没有神话光效。'),('展柜','玻璃、中性墙与素净的第一件衣。'),('素纱与绸','同样素色，直接看布后的木格是否透出。')]
concept_html=''.join(f'<a class="card" href="素材/{n}.png" target="_blank"><img src="素材/{n}.png" loading="lazy" alt="{n}"><div><h3>{n}</h3><p>{d}</p></div></a>' for n,d in concepts)
shots=''
for res in ['1920×1080','1280×720']:
    cards=''.join(f'<a class="card" href="验收/{res}/{p.name}" target="_blank"><img src="验收/{res}/{p.name}" loading="lazy" alt="{escape(p.stem)}"><div><h3>{escape(p.stem[3:])}</h3><p>{res} · 实际操作画面</p></div></a>' for p in sorted((root/'验收'/res).glob('*.png')))
    shots+=f'<div class="grid shot-group" data-resolution="{res}" {"hidden" if res=="1280×720" else ""}>{cards}</div>'
html='''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>华裳 · 效果总览</title><style>
:root{color:#302e29;background:#e8e2d4;font-family:"PingFang SC","Microsoft YaHei",sans-serif}*{box-sizing:border-box}body{margin:0}header{padding:48px 7vw 36px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #c5bdac}h1,h2,h3{font-family:"Songti SC",serif;font-weight:400}h1{font-size:46px;letter-spacing:8px;margin:8px 0 15px}header small{letter-spacing:4px;color:#6c695d}p{line-height:1.8;color:#6c695d;font-size:14px}.launch{display:inline-block;background:#3d5963;color:#faf6ed;text-decoration:none;padding:17px 28px;border-radius:2px}.intro{max-width:740px}.wrap{margin:0 auto;max-width:1700px;padding:44px 7vw}h2{font-size:30px;letter-spacing:3px;margin:0 0 12px}.section-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px}.card{display:block;text-decoration:none;color:inherit;border:1px solid #c5bdac;background:#f2ecdf;transition:transform .2s}.card:hover{transform:translateY(-3px)}.card img{width:100%;display:block;aspect-ratio:16/9;object-fit:cover}.card>div{padding:17px 20px}.card h3{font-size:20px;letter-spacing:2px;margin:0 0 5px}.card p{font-size:12px;margin:0}.chips{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.chip{border:1px solid #b6aa92;padding:8px 13px;font-size:12px;color:#5c6255}.tabs{display:flex;gap:8px}.tabs button{font:inherit;padding:10px 18px;border:1px solid #a79b82;background:transparent;cursor:pointer;color:#4c5249}.tabs button.selected{background:#3d5963;color:#faf6ed;border-color:#3d5963}.links{display:flex;gap:24px;flex-wrap:wrap;margin-top:25px}a{color:#3d5963}.swatches{display:grid;grid-template-columns:repeat(5,1fr);gap:18px;margin:25px 0}.swatch{border:1px solid #c5bdac;padding:15px;background:#f2ecdf;font-size:12px}.swatch i{height:45px;display:block;margin-bottom:12px}.details{border-top:1px solid #c5bdac;margin-top:42px;padding-top:30px}footer{padding:30px 7vw;border-top:1px solid #c5bdac;color:#6c695d;font-size:12px;line-height:1.9}[hidden]{display:none!important}button:focus-visible,a:focus-visible{outline:3px solid #b78343;outline-offset:4px}@media(max-width:1100px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}header{gap:22px}h1{font-size:35px}.swatches{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){header,.section-head{display:block}.grid{grid-template-columns:1fr}.launch{margin-top:20px}.tabs{margin-top:20px}.swatches{grid-template-columns:repeat(2,1fr)}}
</style></head><body><header><div class="intro"><small>一幅素纱 / INDEPENDENT INTERFACE</small><h1>华裳 · 从蚕到神</h1><p>从一匹未染的绢，到木色戏台上的初衣。材料先被看见，建筑退后。</p><div class="chips"><span class="chip">无需安装 · 双击体验</span><span class="chip">六张独立概念图</span><span class="chip">两种尺寸的实际验收画面</span></div></div><a class="launch" href="直接打开.html">打开界面样板 →</a></header><main class="wrap"><div class="section-head"><div><h2>场景与材料</h2><p>点击任意画面查看原图。场景用来定材料、气氛与操作位置。</p></div></div><div class="grid">CONCEPT_HTML</div><div class="details"><div class="section-head"><div><h2>实际点通的首日</h2><p>确认绢 → 浸靛蓝 → 裁上襦与裙 → 留未缝披帛 → 沿缝 → 试衣 → 西施0档 → 单柜预览。</p></div><div class="tabs"><button class="selected" data-res="1920×1080">1920×1080</button><button data-res="1280×720">1280×720</button></div></div>SHOT_HTML</div><div class="details"><h2>界面的纸、木与靛蓝</h2><p>这些颜色是本作的界面规格。布的透与不透请看上面的同色材料图。</p><div class="swatches"><div class="swatch"><i style="background:#E8E2D4"></i>素纸 · #E8E2D4</div><div class="swatch"><i style="background:#302E29"></i>墨灰 · #302E29</div><div class="swatch"><i style="background:#594637"></i>胡桃木 · #594637</div><div class="swatch"><i style="background:#3D5963"></i>靛蓝 · #3D5963</div><div class="swatch"><i style="background:#855039"></i>陶褐 · #855039</div></div><div class="links"><a href="先看这里.md">先看这里</a><a href="设计方案.md">设计取舍</a><a href="风格规范.md">完整风格规范</a><a href="完成标准.md">完成标准</a><a href="验收/验收记录.md">实际检查记录</a><a href="参考与生成记录.md">概念图生成记录</a></div></div></main><footer>独立界面样板，正式规则仍以 docs/00–29 为准，不读取正式存档。<br>场景为3D风格概念图，木牌、库存、工序、示意词条与展柜状态会更新；不运行正式工时、经验和品质结算。单柜只预览，不开幕。</footer><script>document.querySelectorAll('[data-res]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-res]').forEach(x=>x.classList.toggle('selected',x===b));document.querySelectorAll('[data-resolution]').forEach(g=>g.hidden=g.dataset.resolution!==b.dataset.res)}));</script></body></html>'''
(root/'效果总览.html').write_text(html.replace('CONCEPT_HTML',concept_html).replace('SHOT_HTML',shots))
print('效果总览已生成')
